##### Importing all the modulues

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model  import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [10]:
##### Importing the data

In [16]:
data=pd.read_csv('diabetes.csv')

In [17]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [19]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

###### The min value of some feature cannot be zero so we have to change them to their mean

In [20]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

###### No Null value present

###### changing the o to mean

In [21]:
data['BMI']=data['BMI'].replace(0,data['BMI'].mean())
data['Glucose']=data['Glucose'].replace(0,data['Glucose'].mean())
data['Insulin']=data['Insulin'].replace(0,data['Insulin'].mean())
data['BloodPressure']=data['BloodPressure'].replace(0,data['BloodPressure'].mean())
data['BMI']=data['BMI'].replace(0,data['BMI'].mean())
data['SkinThickness']=data['SkinThickness'].replace(0,data['SkinThickness'].mean())

In [22]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.681605      72.254807      26.606479  118.660163   
std       3.369578   30.436016      12.115932       9.631241   93.080358   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.750000      64.000000      20.536458   79.799479   
50%       3.000000  117.000000      72.000000      23.000000   79.799479   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    32.450805                  0.471876   33.240885    0.348958  
std      6.875374                  0.331329   11.760232    0.476951  
min     18.200000                  0.078000   21.000000    0.000000  
25%     27.500000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

###### Insulin has the highest number outlier

##### Independent and Dependent Feature

In [23]:
#Independent Feature
X=data.iloc[:,:-1]

In [24]:
#Dependent feature
y=data['Outcome']

In [25]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0              6    148.0           72.0      35.000000   79.799479  33.6   
1              1     85.0           66.0      29.000000   79.799479  26.6   
2              8    183.0           64.0      20.536458   79.799479  23.3   
3              1     89.0           66.0      23.000000   94.000000  28.1   
4              0    137.0           40.0      35.000000  168.000000  43.1   
..           ...      ...            ...            ...         ...   ...   
763           10    101.0           76.0      48.000000  180.000000  32.9   
764            2    122.0           70.0      27.000000   79.799479  36.8   
765            5    121.0           72.0      23.000000  112.000000  26.2   
766            1    126.0           60.0      20.536458   79.799479  30.1   
767            1     93.0           70.0      31.000000   79.799479  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [26]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [27]:
y.unique()

array([1, 0])

###### As the outcome is in binary(0,1) so we can use Logistic Regression

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=0)

In [29]:
X_train.shape

(514, 8)

In [30]:
X_test.shape

(254, 8)

In [31]:
y_train.shape

(514,)

###### Standardization

In [65]:
import pickle

def scaler_standard(X_train,X_test):
    scaler=StandardScaler()
    X_train_scaled=scaler.fit_transform(X_train)
    X_test_scaled=scaler.fit_transform(X_test)
    
    file=open(r'/config/workspace/Model/StandardScaler.pkl','wb')
    pickle.dump(scaler,file)
    file.close()
    
    return X_train_scaled,X_test_scaled

In [66]:
X_train_scaled,X_test_scaled=scaler_standard(X_train,X_test)

In [67]:
X_train_scaled

array([[ 0.63210007, -0.57367579,  0.59991959, ..., -0.01850593,
         1.21020784, -0.63081654],
       [ 3.8693227 ,  1.31848273, -0.0667174 , ...,  1.18772056,
         1.02855181,  1.14329334],
       [ 0.3378071 ,  0.11141609,  0.43326034, ..., -0.43494126,
        -0.09711999,  0.55192338],
       ...,
       [ 0.04351414, -0.93253344, -0.65002477, ..., -1.13857338,
        -0.96370859, -1.05322365],
       [ 2.1035649 , -1.22614424,  0.09994185, ..., -0.36314207,
        -0.5110575 ,  0.12951627],
       [ 0.3378071 ,  0.43765032,  0.76657884, ..., -0.09137089,
         0.50145153,  3.00188464]])

In [68]:
log_reg=LogisticRegression()

log_reg.fit(X_train_scaled,y_train)

LogisticRegression()

##### Hyperparameter Tuning

In [69]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [70]:
parameters={
    'penalty':['l1','l2'],
    'C'      :np.logspace(-3,3,7),
    'solver' :['newton-cg','lbfgs','liblinear']
}

In [71]:
logreg=LogisticRegression()
clf=GridSearchCV(logreg,
                param_grid=parameters,
                scoring='accuracy',
                cv=10)

clf.fit(X_train_scaled,y_train)

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                         'penalty': ['l1', 'l2'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear']},
             scoring='accuracy')

In [72]:
clf.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [73]:
clf.best_score_

0.7722096530920061

In [74]:
y_pred=clf.predict(X_test_scaled)

In [75]:
conf_matrix=confusion_matrix(y_test,y_pred)
conf_matrix

array([[149,  21],
       [ 39,  45]])

In [76]:
true_positive=conf_matrix[0][0]
true_negative=conf_matrix[1][1]
false_positive=conf_matrix[0][1]
false_negative=conf_matrix[1][0]

In [77]:
print(accuracy_score(y_test,y_pred))

0.7637795275590551


In [78]:
Precision=true_positive/(true_positive+false_positive)
Precision

0.8764705882352941

In [79]:
Recall=true_positive/(true_positive+false_negative)
Recall

0.7925531914893617

In [80]:
F1_Score=2*(Recall*Precision)/(Recall+Precision)
F1_Score

0.8324022346368716

In [81]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       170
           1       0.68      0.54      0.60        84

    accuracy                           0.76       254
   macro avg       0.74      0.71      0.72       254
weighted avg       0.76      0.76      0.76       254



In [49]:
file=open(r'/config/workspace/Model/ForPrediction.pkl','wb')
pickle.dump(log_reg,file)
file.close()